server:
  port: 8080

spring:
  profiles:
    default: h2
  config:
    import: optional:classpath:application-local.yml

app:
  security:
    jwt-secret: "replace-with-strong-secret-at-least-32-chars"
    jwt-expiration-minutes: 180
  auth:
    google-client-id: ""
